import 'package:flutter/material.dart';

ThemeData lightTheme = ThemeData(
  useMaterial3: true,
  colorScheme: ColorScheme.fromSeed(
    seedColor: Colors.black,
    primary: Colors.black,
    onPrimary: Colors.grey[800],
    primaryContainer: Colors.grey[800],
    onPrimaryContainer: Colors.grey[800],
    secondary: Colors.grey[800],
    onSecondary: Colors.grey[800],
    secondaryContainer: Colors.grey[800],
    onSecondaryContainer: Colors.grey[800],
    tertiary: Colors.grey[800],
    onTertiary: Colors.grey[800],
    tertiaryContainer: Colors.grey[800],
    onTertiaryContainer: Colors.grey[800],
    error: Colors.grey[800],
    onError: Colors.grey[800],
    errorContainer: Colors.grey[800],
    onErrorContainer: Colors.grey[800],
    outline: Colors.grey[800],
    outlineVariant: Colors.grey[800],
    background: Colors.grey[800],
    onBackground: Colors.grey[800],
    surface: Colors.grey[800],
    onSurface: Colors.grey[800],
    surfaceVariant: Colors.grey[800],
    onSurfaceVariant: Colors.grey[800],
    inverseSurface: Colors.grey[800],
    onInverseSurface: Colors.grey[800],
    inversePrimary: Colors.grey[800],
    shadow: Colors.grey[800],
    scrim: Colors.grey[800],
    surfaceTint: Colors.grey[800],
  ),
);
