import 'package:flutter/material.dart';

ThemeData lightTheme = ThemeData(
  useMaterial3: true,
  colorScheme: ColorScheme.fromSeed(
    seedColor: Colors.black,
    primary: Colors.black,
    onPrimary: Colors.grey[200],
    primaryContainer: Colors.grey[900],
    onPrimaryContainer: Colors.grey[200],
    secondary: Colors.grey[900],
    onSecondary: Colors.grey[200],
    secondaryContainer: Colors.grey[900],
    onSecondaryContainer: Colors.grey[200],
    tertiary: Colors.grey[900],
    onTertiary: Colors.grey[200],
    tertiaryContainer: Colors.grey[900],
    onTertiaryContainer: Colors.grey[200],
    error: Colors.grey[900],
    onError: Colors.red,
    errorContainer: Colors.grey[900],
    onErrorContainer: Colors.grey[200],
    outline: Colors.grey[900],
    outlineVariant: Colors.grey[900],
    background: Colors.grey[900],
    onBackground: Colors.grey[200],
    surface: Colors.grey[900],
    onSurface: Colors.grey[200],
    surfaceVariant: Colors.grey[900],
    onSurfaceVariant: Colors.grey[200],
    inverseSurface: Colors.grey[900],
    onInverseSurface: Colors.grey[200],
    inversePrimary: Colors.grey[900],
    shadow: Colors.grey[900],
    scrim: Colors.grey[900],
    surfaceTint: Colors.grey[900],
  ),
);
